[toolchain]
profile = "minimal"
channel = "nightly-2026-02-02"
components = ["rust-src", "llvm-tools", "rustfmt", "clippy"]
targets = [
    "riscv64gc-unknown-none-elf",
    "loongarch64-unknown-none-softfloat",
]
